language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  global:
    - secure: Ovy5baEVljesJrAo0J/r5Rg/FbRDOSx26R1fk3NBRgeuB5m7gOcQB9JwhooxRV2DcN+dljQCXh1eurRm3Q/XPeRUoEBAWwQdQhNgYbW2cPW1C8C/aYHIMggV81oh193GO/etRnsWQp5YYEVOVvVP6k6M6EitxoCUzb0c8U+vVA3SbruKR1aLBZV8Dhn+eQIXLCpeFRA7rd+XI9geO5JsxN50ZtpntJ4PwjfOWku4Ml8b2TM263/tDK6OVosRVonfXY9VOJkbpWu4VJQiT0jkSRUiw9A2Qdafd3gFE/O9pCJR52L+qwwXtf5iL+7hYaumX8upI9mHSiX55SpJobSuZiLX1g1PkE1DDRk6kUve/pY8aTNzGkJqBUrRb3oqk8V+RvMlpsEO5cZFJFVnAdxVdiEsiOR/CtKJLYxZtw6k1gLB8N++JHf7SOnsbY5jhNrbDvuW0+p+MWkvVH1q/PrWOMp/9O2Pfe7TdYY6h3UB2neLG7YrKlvwWoHWkq4k4Q81XM7AEDddohQopNUDQxoPbkQBZYqSMV92AV+8B/YyuN4ejZG+EwQ3zd3Y7xLIeU1DO8wlA96oqC2GGL5+S5rNK/BKRwji7BE7P+4w0SlZH78wfug1xgzJCi/nTrkbAq7CmYZ1dmYD6grwHAAX4ollzzWzL/h2RfLa5LpTt8jSmWs=
install:
  - composer install
script: phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry vendor/bin/coveralls -v
notifications:
  email:
  - peter279k@gmail.com
