language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  global:
    - secure: VcLKIuUbziy907gUQIU+kU8v0c68OzuY9gkSccfVAKftRRlW5Qmws9HViPsNCRHrD5iG4hsZMDFb6nnDE5ScPj0MVcUHS6A8dGDNSisFTVscmlkpSmnjTZ6x4RdRVLj6N7H8ALUDMrAWsczDNotUpTTrqm79jI/IX/DyFK+IdHM3GtNjGLziRWl+MwqOlSppb1/9frA9KBr0oTG5Y8fRj9TMkhW1Ebzo+/b3AyI5Hdg3zykikCUAz4CwPWvPrG8qotajQhXE0rZa+TS/FRGzD5oB/QXewE2y3U9IBbxyg1aUQeCo1YhhxJzS2umFSkECNm1o08AhZmNQVZpXL15MfudFDaNjPPRPvmUweN0obqc5vh+1w2LZqzs66SXxI5KYvOuD7o+w8bKygfuWeo9PHvG12/2LkdPrEn77YpAV0tjBuCNO0wRTwtq04sILHHeH4Osh+7RSKSsKVAYtw+NjdVNVJ3S5jGrUlmWptkk+D1eENcJyCg8ruiDa5AI3e6EMfBXzOY+pTSikXmXK7fX8o6SWRBd+syV2BbHH2qtvLW5uYPtkRzg/9yWcKsYsIfMiJp+U4EwIqdfB+Ht038TH2BUJftCxveB6nhhZwRnd1oelb1L1ycEasIeUXHWm++8JXGpsyV2v5hva67WC7ulf+DabWClshiwONJo7+0Wzuz0=
install:
  - composer install
script: phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry vendor/bin/coveralls -v
notifications:
  email:
  - peter279k@gmail.com
